### ISSUE TITLE
Responses with primitives cause type clash

### ISSUE THREAD

**Issue by mojadev** [mojadev/pakt#37]
**Steps to reproduce**

* Create an api with the following response:  
  ```yaml
        404:
          description: Unknown template
          content: 
            application/json:
              schema:
                type: string  
   ```
* Generate the router
* Behaviour: A type error is thrown due to responses only allowing objects
* **Expected behaviour**: String responses are supported
